# Generated by Django 3.1.7 on 2021-03-18 09:40

from django.db import migrations, models
import portfolio_site_resume.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Site Name')),
                ('siteurl', models.URLField(max_length=120, verbose_name='Site Url')),
                ('image', models.ImageField(null=True, upload_to=portfolio_site_resume.models.get_image_path, verbose_name='Site Image')),
            ],
        ),
    ]
