# Generated by Django 3.1.7 on 2021-03-18 09:40

from django.db import migrations, models
import personal_info.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('skill1', models.CharField(blank=True, max_length=120, verbose_name='First Skill')),
                ('skill2', models.CharField(blank=True, max_length=120, verbose_name='Second Skill')),
                ('skill3', models.CharField(blank=True, max_length=120, verbose_name='Third Skill')),
                ('skill4', models.CharField(blank=True, max_length=120, verbose_name='Fourth Skill')),
                ('prof_img', models.ImageField(upload_to=personal_info.models.get_image_path, verbose_name='Profile Image')),
                ('background_img', models.ImageField(upload_to=personal_info.models.get_image_path, verbose_name='Background Image')),
                ('linkedin_link', models.URLField(max_length=120, null=True, verbose_name='Social Media (Linkedin)')),
                ('instagram_link', models.URLField(max_length=120, null=True, verbose_name='Social Media (Instagram)')),
                ('telegram_link', models.URLField(max_length=120, null=True, verbose_name='Social Media (Telegram)')),
            ],
        ),
    ]
